### ISSUE TITLE
Renaming

### ISSUE THREAD

**Issue by blvckfxck** [TomDankel/Go-TaskScheduler#1]
Rename: - Multithreading interface --> Task
              - Thread --> TaskI

**Comment by kafrgebhardt** [comment]
OK


Sincerely -- Cordialement -- Atentamente -- Mit freundlichem Gruß

Karl Friedrich Gebhardt
***@***.***

**Comment by blvckfxck** [comment]
rename Continue --> Resume, play --> PLayfunction, checkChanel unexported
