### ISSUE TITLE
Controll function creates Deadlock

### ISSUE THREAD

**Issue by blvckfxck** [TomDankel/Go-TaskScheduler#7]
The usage of the channels within the controll function in the Task package creates a deadlock.

**Comment by kafrgebhardt** [comment]
Hello,

wollen Sie mir dazu mal den Code schicken?

Sincerely -- Cordialement -- Atentamente -- Mit freundlichem Gruß

Karl Friedrich Gebhardt
***@***.***

**Comment by blvckfxck** [comment]
@TomDankel bug is fixed
